language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "node"
  
before_script:
  - npm install -g gulp-cli
cache: npm
notifications:
  email: false
# script: npm run-script pretest && npm run-script coverage
# after_script: npx coveralls < coverage/lcov.info